import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import type {ServerResponse} from 'node:http';
import handler from '../api/assistant';
type Request=Parameters<typeof handler>[0];
async function call(method:string,body?:unknown,extra:Record<string,string|undefined>={}){let payload='',status=200;const req=Object.assign(Readable.from([]),{method,body,headers:{host:'localhost',origin:'http://localhost','content-type':'application/json','sec-fetch-site':'same-origin',...extra}}) as Request;const res={setHeader(){},get statusCode(){return status;},set statusCode(s:number){status=s;},end(s:string){payload=s;}} as unknown as ServerResponse;await handler(req,res);return {status,body:JSON.parse(payload)};}
test('AI is unavailable without its server key and needs no access password',async()=>{delete process.env.GEMINI_API_KEY;delete process.env.APP_ACCESS_PASSWORD;assert.deepEqual((await call('GET')).body,{configured:false});assert.equal((await call('POST',{task:'coach',text:'hello'})).status,503);process.env.GEMINI_API_KEY='test-only';assert.deepEqual((await call('GET')).body,{configured:true});delete process.env.GEMINI_API_KEY;});
test('passwordless same-origin JSON, input/output validation and quota',async context=>{process.env.GEMINI_API_KEY='test-only';process.env.GEMINI_MODEL='gemini-3.5-flash-lite';context.after(()=>{delete process.env.GEMINI_API_KEY;delete process.env.GEMINI_MODEL;});
 const fetchMock=context.mock.method(globalThis,'fetch',async(_url:unknown,options?:RequestInit)=>{const data=JSON.parse(options?.body as string);assert.ok(data.systemInstruction.parts[0].text.includes('1600kcal'));return new Response(JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify({foods:[{name:'ご飯',portion:'150g',kcal:234,protein:3.8,fat:0.5,carbs:55.7,estimated:false,note:'量は推定'}]})}]}}]}),{status:200});});
 assert.equal((await call('POST',{task:'coach',text:'hello'},{origin:undefined})).status,403);
 assert.equal((await call('POST',{task:'coach',text:'hello'},{origin:'https://another.example'})).status,403);
 assert.equal((await call('POST',{task:'coach',text:'hello'},{origin:'null'})).status,403);
 assert.equal((await call('POST',{task:'coach',text:'hello'},{'sec-fetch-site':'cross-site'})).status,403);
 assert.equal((await call('POST',{task:'coach',text:'hello'},{'content-type':'text/plain'})).status,415);
 assert.equal(fetchMock.mock.callCount(),0);
 assert.equal((await call('POST',{task:'invalid',text:'hello'})).status,400);
 assert.equal((await call('POST',{task:'food',text:'a',image:'data:text/html;base64,abc'})).status,400);
 for(const [mode,word] of [['gentle','やさしめ'],['balanced','バランス'],['direct','厳しめ']]){await call('POST',{task:'coach',text:'夕食は？',context:{settings:{coachMode:mode}}});const data=JSON.parse(fetchMock.mock.calls.at(-1)!.arguments[1]!.body as string);assert.ok(data.systemInstruction.parts[0].text.includes(word));assert.ok(!data.systemInstruction.parts[0].text.includes('目的は七五三'));}
 for(const history of [[{role:'model',text:'a'},{role:'user',text:'b'}],[{role:'user',text:'a'}],[{role:'user',text:'a'},{role:'model',text:''}],[{role:'system',text:'a'},{role:'model',text:'b'}],Array.from({length:10},(_,i)=>({role:i%2?'model':'user',text:'x'}))])assert.equal((await call('POST',{task:'coach',text:'続き',history})).status,400);
 const before=fetchMock.mock.callCount();assert.equal((await call('POST',{task:'coach',text:'鶏肉以外だと？',history:[{role:'user',text:'夕食は？'},{role:'model',text:'鶏胸肉のポン酢蒸し'}]})).status,200);assert.equal(fetchMock.mock.callCount(),before+1);
 const sent=JSON.parse(fetchMock.mock.calls.at(-1)!.arguments[1]!.body as string);assert.deepEqual(sent.contents.map((c:{role:string})=>c.role),['user','model','user']);assert.equal(sent.contents[1].parts[0].text,'鶏胸肉のポン酢蒸し');assert.ok(sent.systemInstruction.parts[0].text.includes('プロテインは食事で不足する日の補助'));
 const result=await call('POST',{task:'food',text:'ご飯',context:{}});assert.equal(result.status,200);assert.equal(result.body.foods[0].kcal,234);assert.equal(result.body.foods[0].estimated,true);
 fetchMock.mock.mockImplementation(async()=>new Response(JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify({brief:{headline:'一歩ずつ',summary:'朝の平均で確認。',tips:['体重を記録']}})}]}}]}),{status:200}));
 const brief=await call('POST',{task:'brief',text:'今日の作戦',context:{homeReport:{forecast:null}}});assert.equal(brief.status,200);assert.equal(brief.body.brief.headline,'一歩ずつ');const briefSent=JSON.parse(fetchMock.mock.calls.at(-1)!.arguments[1]!.body as string);assert.equal(briefSent.generationConfig.responseMimeType,'application/json');assert.match(briefSent.contents[0].parts[0].text,/体重数値を作らない/);
 fetchMock.mock.mockImplementation(async()=>new Response(JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify({brief:{headline:'x',summary:'x',tips:['x'.repeat(201)]}})}]}}]}),{status:200}));assert.equal((await call('POST',{task:'brief',text:'今日の作戦'})).status,502);
 fetchMock.mock.mockImplementation(async()=>new Response(JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify({exercises:[{name:'ジムで筋トレ',minutes:40.4,met:3.54,details:'チェストプレス30kg 10回×3',note:''},{name:'バイク',minutes:20,met:6}]})}]}}]}),{status:200}));
 const ex=await call('POST',{task:'exercise',text:'チェストプレス30kg10回3セットとバイク20分',context:{}});assert.equal(ex.status,200);assert.deepEqual(ex.body.exercises,[{name:'ジムで筋トレ',minutes:40,met:3.5,details:'チェストプレス30kg 10回×3',note:''},{name:'バイク',minutes:20,met:6,details:'',note:''}]);
 const exSent=JSON.parse(fetchMock.mock.calls.at(-1)!.arguments[1]!.body as string);assert.equal(exSent.generationConfig.responseMimeType,'application/json');assert.match(exSent.contents[0].parts[0].text,/実際に行ったと述べた運動だけ/);
 for(const bad of [{name:'x',minutes:0,met:3},{name:'x',minutes:30,met:20},{name:'',minutes:30,met:3},{name:'x',minutes:'30',met:3}]){fetchMock.mock.mockImplementation(async()=>new Response(JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify({exercises:[bad]})}]}}]}),{status:200}));assert.equal((await call('POST',{task:'exercise',text:'運動'})).status,502);}
 fetchMock.mock.mockImplementation(async()=>new Response(JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify({body:{kg:86,bodyFat:24.7,muscle:39.7,visceral:14,bmr:1810,bodyAge:420,water:null,bone:'3.4'},note:'chocoZAPの結果画面'})}]}}]}),{status:200}));
 const png='data:image/png;base64,iVBORw0KGgo=';const scale=await call('POST',{task:'body',text:'',image:png,context:{}});assert.equal(scale.status,200);assert.deepEqual(scale.body.body,{kg:86,bodyFat:24.7,muscle:39.7,visceral:14,bmr:1810});assert.equal(scale.body.note,'chocoZAPの結果画面');
 const scaleSent=JSON.parse(fetchMock.mock.calls.at(-1)!.arguments[1]!.body as string);assert.equal(scaleSent.generationConfig.responseMimeType,'application/json');assert.match(scaleSent.contents[0].parts[0].text,/推測せずnull/);assert.ok(scaleSent.contents[0].parts[1].inlineData);
 fetchMock.mock.mockImplementation(async()=>new Response(JSON.stringify({candidates:[{content:{parts:[{text:'{"foods":[{"name":"bad","kcal":-99}]}'}]}}]}),{status:200}));assert.equal((await call('POST',{task:'food',text:'ご飯'})).status,502);
 fetchMock.mock.mockImplementation(async()=>new Response('{}',{status:429}));assert.equal((await call('POST',{task:'coach',text:'夕食は？'})).status,429);
 fetchMock.mock.mockImplementation(async()=>new Response(JSON.stringify({candidates:[{content:{parts:[{text:'回答'}]}}]}),{status:200}));
 let limited=false;for(let i=0;i<31;i++){const r=await call('POST',{task:'coach',text:'夕食は？'});if(r.status===429){limited=true;break;}assert.equal(r.status,200);}assert.equal(limited,true);const calls=fetchMock.mock.callCount();assert.equal((await call('POST',{task:'coach',text:'夕食は？'})).status,429);assert.equal(fetchMock.mock.callCount(),calls);
});
