const {chromium}=await import(process.env.BODY_QUEST_PLAYWRIGHT??'playwright');
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import fs from 'node:fs/promises';
const server=spawn('npm',['run','dev','--','--host','127.0.0.1'],{stdio:'inherit'});
const day=new Date().toISOString().slice(0,10),deadline=new Date(Date.parse(day+'T12:00:00Z')+51*86400000).toISOString().slice(0,10);
let browser;
try {
 for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:5173')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch(process.env.BODY_QUEST_CHROMIUM?{executablePath:process.env.BODY_QUEST_CHROMIUM,args:['--no-sandbox']}:{});
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const saved=()=>page.getByText('端末に保存済み',{exact:true}).waitFor({state:'attached'});
 const nav=name=>page.locator('.bottom-nav').getByRole('button',{name,exact:true}).click();
 const state=()=>page.evaluate(async()=>{const db=await new Promise((r,j)=>{const q=indexedDB.open('body-quest',1);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});return new Promise((r,j)=>{const q=db.transaction('data').objectStore('data').get('state');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});});
 await page.goto('http://127.0.0.1:5173');await page.getByRole('heading',{name:'今日のクエスト'}).waitFor();await saved();
 assert.equal((await state()).settings.energy,undefined);
 await page.evaluate(()=>document.documentElement.style.setProperty('--safe-area-top','59px'));
 assert.ok((await page.locator('.header-settings').boundingBox()).y>=59);
 await page.getByRole('button',{name:'目標を設定する',exact:true}).click();
 await page.getByLabel('身長（cm）',{exact:true}).fill('182');await page.getByLabel('年齢',{exact:true}).fill('42');
 await page.getByLabel('開始体重（kg）',{exact:true}).fill('88');await page.getByLabel('目標体重（kg）',{exact:true}).fill('80');
 await page.getByLabel('目標・イベントの名前',{exact:true}).fill('旅行に向けて');
 await page.getByRole('button',{name:'1年後',exact:true}).click();
 assert.equal((await page.getByLabel('目標日',{exact:true}).inputValue()).slice(0,4),String(new Date().getUTCFullYear()+1));
 await page.getByLabel('目標日',{exact:true}).fill(deadline);
 await page.getByRole('button',{name:'目標と食事プランを保存',exact:true}).click();await saved();
 const configured=await state();assert.equal(configured.settings.targetWeight,80);assert.equal(configured.settings.nutritionMode,'auto');assert.equal(configured.settings.protein,Math.floor(configured.settings.kcal*.3/4));
 await page.getByText('61,600',{exact:false}).first().waitFor();await page.getByText('1,208',{exact:false}).first().waitFor();
 for(const name of ['1日','1週','2週','30日','期限まで']){await page.getByRole('button',{name,exact:true}).click();await page.getByText(/確定 0日/).waitFor();}
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await nav('今日');await page.getByText(`自動目標 ${configured.settings.kcal.toLocaleString('ja-JP')} kcal`,{exact:true}).waitFor();
 await nav('食事');await page.getByRole('button',{name:'ご飯をお気に入りに登録',exact:true}).click();await saved();
 await page.getByRole('button',{name:'お気に入り',exact:true}).click();assert.equal(await page.locator('.food-item').count(),1);
 await page.getByRole('button',{name:'ご飯を1食追加',exact:true}).click();await saved();
 await page.getByRole('button',{name:'ハイボール',exact:true}).click();await page.getByLabel('杯数',{exact:true}).fill('3');
 await page.getByRole('button',{name:'飲酒を記録',exact:true}).click();await saved();
 const complete=()=>page.getByLabel('この日の食事・飲酒・運動をすべて記録した');
 await complete().check();await saved();assert.equal(Object.keys((await state()).closedDays).length,1);
 await nav('計画');await page.getByRole('button',{name:'1日',exact:true}).click();await page.getByRole('img',{name:/確定した1日分の累積赤字/}).waitFor();
 await nav('食事');await page.getByRole('button',{name:'ご飯を1食追加',exact:true}).click();await saved();assert.equal(await complete().isChecked(),false);
 await complete().check();await saved();await nav('運動');
 await page.getByLabel('運動・メニュー',{exact:true}).fill('筋トレ');await page.getByLabel('時間（分）',{exact:true}).fill('30');
 await page.getByLabel('運動強度・消費の目安',{exact:true}).selectOption('3.5');await page.getByRole('button',{name:'運動を保存',exact:true}).click();await saved();
 assert.equal((await state()).exercises[0].netKcal,110);assert.equal(Object.keys((await state()).closedDays).length,0);
 await nav('食事');await complete().check();await saved();const expenditure=Object.values((await state()).closedDays)[0].expenditure;assert.equal(expenditure,2285);
 await nav('今日');await page.getByRole('button',{name:'体重を記録',exact:true}).first().click();await page.getByLabel('体重（kg）',{exact:true}).fill('86');await page.getByRole('button',{name:'体重を保存',exact:true}).click();await saved();
 assert.notEqual((await state()).settings.kcal,configured.settings.kcal);assert.equal(Object.values((await state()).closedDays)[0].expenditure,expenditure);
 await nav('計画');await page.getByRole('button',{name:'計画を編集',exact:true}).click();
 await page.getByRole('button',{name:'自分で調整',exact:true}).click();await page.getByLabel('カロリー（kcal）',{exact:true}).fill('2000');await page.getByLabel('たんぱく質（g）',{exact:true}).fill('130');
 await page.getByRole('button',{name:'目標と食事プランを保存',exact:true}).click();await saved();assert.equal((await state()).settings.protein,130);
 await nav('コーチ');await page.getByRole('button',{name:/^厳しめ/}).click();await saved();assert.equal((await state()).settings.coachMode,'direct');
 let payload;await page.route('**/api/assistant',async route=>{if(route.request().method()==='POST'){payload=route.request().postDataJSON();await route.fulfill({json:{text:'目標と現在のプランの差を確認しました。'}});}else await route.fulfill({json:{configured:true}});});
 await page.getByRole('button',{name:'相談する',exact:true}).click();await page.getByText('目標と現在のプランの差を確認しました。',{exact:true}).waitFor();
 assert.equal(payload.context.settings.coachMode,'direct');assert.equal(payload.context.settings.goalName,'旅行に向けて');assert.equal(payload.context.energyPlan.periods.length,5);
 await page.reload();await page.getByRole('heading',{name:'今日のクエスト'}).waitFor();await saved();assert.equal((await state()).meals.length,3);assert.equal((await state()).settings.kcal,2000);assert.equal((await state()).favorites[0],'rice150');
 await page.locator('.header-settings').click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'食事記録をCSVで出力',exact:true}).click();assert.match((await download).suggestedFilename(),/\.csv$/);
 await fs.mkdir('test-artifacts',{recursive:true});
 for(const width of [390,320]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:`test-artifacts/goal-form-${width}.png`,fullPage:true});}
 assert.deepEqual(errors,[]);
 console.log('PASS: 320/390px, profile, 1-year/event goals, automatic PFC and weight updates, manual mode, favorites, week report, closure invalidation, historical snapshots, coach tone payload, CSV, reload');
} finally {if(browser)await browser.close();server.kill('SIGTERM');}
