import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import fs from 'node:fs/promises';
const server=spawn('npm',['run','dev','--','--host','127.0.0.1'],{stdio:'inherit'});
let browser;
try {
 for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:5173')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch();
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 const page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const saved=()=>page.getByText('端末に保存済み',{exact:true}).waitFor({state:'attached'});
 const nav=name=>page.locator('.bottom-nav').getByRole('button',{name,exact:true}).click();
 const state=()=>page.evaluate(async()=>{const db=await new Promise((r,j)=>{const q=indexedDB.open('body-quest',1);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});return new Promise((r,j)=>{const q=db.transaction('data').objectStore('data').get('state');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});});
 await page.goto('http://127.0.0.1:5173');
 await page.getByRole('heading',{name:'今日のクエスト'}).waitFor();await saved();
 await page.evaluate(()=>document.documentElement.style.setProperty('--safe-area-top','59px'));
 assert.ok((await page.locator('.header-settings').boundingBox()).y>=59);
 await nav('計画');
 await page.getByRole('heading',{name:'目標から逆算する'}).waitFor();
 await page.getByRole('button',{name:'計画を編集',exact:true}).click();
 await page.getByRole('button',{name:'開始88kg → 目標80kgにする',exact:true}).click();
 await page.getByLabel('開始日',{exact:true}).fill('2026-10-02');
 await page.getByLabel('期限（この日の朝）',{exact:true}).fill('2026-11-22');
 await page.getByRole('button',{name:'計画を保存',exact:true}).click();await saved();
 assert.equal((await state()).settings.targetWeight,80);
 await page.getByText('61,600',{exact:false}).first().waitFor();
 await page.getByText('1,208',{exact:false}).first().waitFor();
 for(const name of ['1日','1週','2週','30日','期限まで']){await page.getByRole('button',{name,exact:true}).click();await page.getByText(/確定 0日/).waitFor();}
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await nav('食事');
 await page.getByRole('button',{name:'ご飯を1食追加',exact:true}).click();await saved();
 await page.getByRole('button',{name:'ハイボール',exact:true}).click();
 await page.getByLabel('杯数',{exact:true}).fill('3');
 await page.getByRole('button',{name:'飲酒を記録',exact:true}).click();await saved();
 const complete=()=>page.getByLabel('この日の食事・飲酒・運動をすべて記録した');
 await complete().check();await saved();assert.equal(Object.keys((await state()).closedDays).length,1);
 await nav('計画');await page.getByRole('button',{name:'1日',exact:true}).click();
 await page.getByRole('img',{name:/確定した1日分の累積赤字/}).waitFor();
 await nav('食事');await page.getByRole('button',{name:'ご飯を1食追加',exact:true}).click();await saved();
 assert.equal(await complete().isChecked(),false);
 await complete().check();await saved();
 await nav('運動');
 await page.getByLabel('運動・メニュー',{exact:true}).fill('筋トレ');
 await page.getByLabel('時間（分）',{exact:true}).fill('30');
 await page.getByLabel('運動強度・消費の目安',{exact:true}).selectOption('3.5');
 await page.getByRole('button',{name:'運動を保存',exact:true}).click();await saved();
 const exercised=await state();assert.equal(exercised.exercises[0].netKcal,110);
 assert.equal(Object.keys(exercised.closedDays).length,0);
 await nav('食事');await complete().check();await saved();
 const expenditure=Object.values((await state()).closedDays)[0].expenditure;
 assert.equal(expenditure,2285);
 await nav('計画');await page.getByRole('button',{name:'計画を編集',exact:true}).click();
 await page.getByLabel('日常活動係数',{exact:true}).selectOption('1.35');
 await page.getByLabel('運動の消費の扱い',{exact:true}).selectOption('included');
 await page.getByRole('button',{name:'計画を保存',exact:true}).click();await saved();
 assert.equal(Object.values((await state()).closedDays)[0].expenditure,expenditure);
 let payload;
 await page.route('**/api/assistant',async route=>{if(route.request().method()==='POST'){payload=route.request().postDataJSON();await route.fulfill({json:{text:'目標に必要な赤字と週の食事配分を確認しました。'}});}else await route.fulfill({json:{configured:true}});});
 await page.getByRole('button',{name:'この数字でAIに相談',exact:true}).click();
 await page.getByRole('button',{name:'相談する',exact:true}).click();
 await page.getByText('目標に必要な赤字と週の食事配分を確認しました。',{exact:true}).waitFor();
 assert.equal(payload.context.energyPlan.goal.total,61600);
 assert.equal(payload.context.energyPlan.periods.length,5);
 await page.reload();await page.getByRole('heading',{name:'今日のクエスト'}).waitFor();await saved();
 assert.equal((await state()).meals.length,3);assert.equal((await state()).settings.targetWeight,80);
 await nav('計画');
 for(const width of [390,320]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
 await fs.mkdir('test-artifacts',{recursive:true});
 await page.screenshot({path:'test-artifacts/energy-plan-320.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'test-artifacts/energy-plan-390.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('PASS: mobile 320/390, safe area, goal profile, 5 periods, completion invalidation, exercise, historical snapshots, AI context, reload persistence');
} finally {if(browser)await browser.close();server.kill('SIGTERM');}
