import {test} from 'node:test';
import assert from 'node:assert/strict';
import {freshState,offsetDate,validateState} from '../src/domain';
import {defaultEnergy} from '../src/energy';
import {applyBrief,briefPhase,homeReport,homeSignature,validAdvice} from '../src/homeCoach';
import type {AppState,HomeBriefRecord,Meal} from '../src/types';
const date='2026-10-01';
function fixture(){const s=freshState();s.settings={...s.settings,startWeight:80,targetWeight:75,startDate:'2026-09-01',deadline:'2027-09-01',energy:defaultEnergy,kcal:2000};return s;}
const meal=(d:string,slot='朝食',name='いつもの納豆ご飯',kcal=400):Meal=>({id:crypto.randomUUID(),date:d,slot,name,kcal,protein:15,fat:10,carbs:50,quantity:1,source:'test',estimated:true});
function weights(s:AppState,loss=.3){for(let i=0;i<14;i++)s.weights.push({id:`w${i}`,date:offsetDate(date,-i),time:'朝',kg:i<7?80-loss:80});}
const brief={headline:'一歩ずつ',summary:'記録を確認しよう',tips:['朝の体重を記録']};
test('home phases and missing weight actions follow the clock, including last night',()=>{assert.equal(briefPhase(10),'morning');assert.equal(briefPhase(11),'afternoon');assert.equal(briefPhase(17),'evening');const s=fixture();const am=homeReport(s,date,8);assert.ok(am.actions.some(a=>a.date===date&&a.time==='朝'));assert.ok(am.actions.some(a=>a.date===offsetDate(date,-1)&&a.time==='夜'));assert.ok(homeReport(s,date,19).actions.some(a=>a.date===date&&a.time==='夜'));s.weights.push({id:'n',date,time:'夜',kg:81});assert.ok(!homeReport(s,date,19).actions.some(a=>a.date===date&&a.time==='夜'));});
test('week-ahead estimate requires both weeks of morning data and never uses nights',()=>{const s=fixture();weights(s);const report=homeReport(s,date,8);assert.equal(report.forecast,79.4);assert.match(report.summary,/目安/);s.weights.push({id:'n',date,time:'夜',kg:90});assert.equal(homeReport(s,date,19).forecast,79.4);s.weights=s.weights.filter(w=>w.time==='夜'||w.date>offsetDate(date,-9));assert.equal(homeReport(s,date,19).forecast,null);});
test('rapid loss and maintenance do not produce a celebratory weight-loss forecast',()=>{const s=fixture();weights(s,1.5);assert.equal(homeReport(s,date,8).tooFast,true);assert.equal(homeReport(s,date,8).forecast,null);assert.match(homeReport(s,date,8).summary,/さらに食事を削らず/);s.settings.targetWeight=80;s.weights=[];weights(s);assert.equal(homeReport(s,date,8).forecast,null);});
test('overeating is evaluated only on a confirmed day, and no skipped meals are proposed',()=>{const s=fixture(),y=offsetDate(date,-1);s.meals=[meal(y,'夕食','外食',2500)];assert.ok(!homeReport(s,date,12).summary.includes('500kcal'));s.closedDays={[y]:{weight:80,expenditure:2200}};assert.match(homeReport(s,date,12).summary,/500kcal/);assert.match(homeReport(s,date,12).summary,/食事を抜いて取り返さず/);});
test('weekly advice requires confirmed days and the selected profile intake bound',()=>{const s=fixture();s.settings.kcal=2200;s.settings.energy={...defaultEnergy,activity:1.5};s.meals=[meal('2026-09-28','夕食','食事',2200),meal('2026-09-29','夕食','食事',2200),meal('2026-09-30','夕食','食事',2200)];assert.equal(homeReport(s,date,12).weekly.suggestedKcal,null);s.closedDays=Object.fromEntries(['2026-09-28','2026-09-29','2026-09-30'].map(d=>[d,{weight:80,expenditure:2600}]));assert.equal(homeReport(s,date,12).weekly.suggestedKcal,2200);s.meals.push(meal('2026-09-30','間食','追加',1600));assert.equal(homeReport(s,date,12).weekly.suggestedKcal,null);});
test('usual-meal prompts require repeated records in that slot, and disappear when logged',()=>{const s=fixture();s.meals=[meal(offsetDate(date,-1)),meal(offsetDate(date,-2)),meal(offsetDate(date,-3),'夕食','カレー'),meal(offsetDate(date,-4),'夕食','カレー')];assert.match(homeReport(s,date,8).actions.find(a=>a.kind==='meal')!.label,/納豆ご飯/);assert.equal(homeReport(s,date,12).actions.find(a=>a.kind==='meal')!.label,'昼食を記録しよう');s.meals.push(meal(date));assert.ok(!homeReport(s,date,8).actions.some(a=>a.kind==='meal'));});
test('brief cache signatures change for health records, but not for auto-update or cache changes',()=>{const s=fixture(),sig=homeSignature(s,date,'morning');s.settings.homeAiAuto=true;assert.equal(homeSignature(s,date,'morning'),sig);s.homeBriefs=[];assert.equal(homeSignature(s,date,'morning'),sig);s.meals.push(meal(date));assert.notEqual(homeSignature(s,date,'morning'),sig);assert.notEqual(homeSignature(s,date,'evening'),homeSignature(s,date,'morning'));});
test('an old brief reply cannot overwrite a replacement request',()=>{const r:HomeBriefRecord={id:'new',date,phase:'morning',attemptedAt:new Date().toISOString()};assert.deepEqual(applyBrief([r],'old',{brief,signature:'s',at:r.attemptedAt}),[r]);assert.equal(applyBrief([r],'new',{brief,signature:'s',at:r.attemptedAt})[0].brief,brief);assert.equal(applyBrief([r],'new',{error:'offline'})[0].error,'offline');});
test('backups preserve optional AI settings/cache; invalid or oversized cache is rejected',()=>{const s=fixture();assert.ok(validateState(s));s.settings.homeAiAuto=true;s.homeBriefs=[{id:'b',date,phase:'morning',attemptedAt:new Date().toISOString(),brief,briefSignature:'123',generatedAt:new Date().toISOString()}];assert.equal(validateState(s).homeBriefs?.[0].brief?.headline,brief.headline);assert.equal(validAdvice({...brief,tips:['x'.repeat(201)]}),false);assert.throws(()=>validateState({...s,homeBriefs:[{...s.homeBriefs![0],phase:'oops'}]}));assert.throws(()=>validateState({...s,homeBriefs:Array.from({length:91},()=>s.homeBriefs![0])}));});

test('reached or expired goals do not predict additional weight loss as a goal',()=>{const s=fixture();weights(s);s.settings.targetWeight=79.8;assert.equal(homeReport(s,date,8).forecast,null);s.settings.targetWeight=75;s.settings.deadline=date;assert.equal(homeReport(s,date,8).forecast,null);});
