import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import fs from 'node:fs/promises';
const {chromium}=await import(process.env.BODY_QUEST_PLAYWRIGHT??'playwright');
const server=spawn('node',['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','4192'],{stdio:'inherit'});
let browser,page;
try {
 for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:4192')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch(process.env.BODY_QUEST_CHROMIUM?{executablePath:process.env.BODY_QUEST_CHROMIUM,args:['--no-sandbox']}:{});page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));
 const state=()=>page.evaluate(async()=>{const db=await new Promise((r,j)=>{const q=indexedDB.open('body-quest',1);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});return new Promise((r,j)=>{const q=db.transaction('data').objectStore('data').get('state');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});});
 const until=async(check,label)=>{for(let i=0;i<100;i++){const s=await state();if(s&&check(s))return s;await new Promise(r=>setTimeout(r,50));}throw Error('not persisted: '+label);};
 const nav=()=>page.locator('.bottom-nav').getByRole('button',{name:'食事',exact:true}).click();
 const values={kcal:193,protein:30,fat:0,carbs:18.5},product={id:'web-milk',name:'メーカー確認済み カフェラテ P30 430ml',portion:'1本（430ml）',category:'マイ食品',source:'メーカーの栄養表示',estimated:false,...values,nutrition:{kind:'manufacturer',portion:'1本（430ml）',values,preparation:'ready',url:'https://www.meiji.co.jp/products/sports/4902705128804.html',title:'商品公式',checkedAt:'2026-10-08T00:00:00Z'}};
 let release,waiting;const slow=new Promise(r=>release=r);
 await page.route('**/api/assistant',async route=>{if(route.request().method()!=='POST')return route.fulfill({json:{configured:true}});const body=route.request().postDataJSON();requests.push(body);if(body.task==='foodSearch'){if(body.text==='遅い検索'){waiting=true;await slow;}return route.fulfill({json:{foods:[product],sources:[{title:'公式商品ページ',url:product.nutrition.url}],searchedAt:'2026-10-08T00:00:00Z',note:'味・容量・基準量をご確認ください'}});}return route.fulfill({status:503,json:{error:'test'}});});
 await page.goto('http://127.0.0.1:4192');await page.getByRole('heading',{name:'今日のクエスト'}).waitFor();await until(s=>!!s,'initial');await nav();await page.getByRole('button',{name:'食品・メーカーを探す',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('食品名・JAN・メーカーURL',{exact:true}).fill('鶏むね 生');await dialog.getByText(/標準食品 2,537件/).waitFor();const raw=dialog.locator('[data-food-id="mext-11220"]');await raw.locator('.catalog-select').click();dialog=page.getByRole('dialog');await dialog.getByLabel('食べた量（g）',{exact:true}).fill('');assert.equal(await dialog.getByRole('button',{name:'食事に追加',exact:true}).isDisabled(),true);assert.deepEqual(errors,[]);await dialog.getByLabel('食べた量（g）',{exact:true}).fill('200');assert.equal(await dialog.getByLabel('基準量の何倍？',{exact:true}).inputValue(),'2');await dialog.getByRole('button',{name:'食事に追加',exact:true}).click();
 let s=await until(s=>s.meals.length===1,'raw 200g');assert.equal(s.meals[0].kcal,210);assert.equal(s.meals[0].protein,46.6);assert.equal(s.meals[0].foodId,'mext-11220');assert.equal(s.meals[0].nutrition.kind,'composition');assert.ok(s.meals[0].nutrition.url.includes('11220'));assert.equal(requests.filter(r=>r.task==='foodSearch').length,0);
 await page.getByRole('button',{name:'食品・メーカーを探す',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('食品名・JAN・メーカーURL',{exact:true}).fill('カフェラテ430ml');await dialog.getByRole('button',{name:'メーカー表示を検索',exact:true}).click();await dialog.locator('[data-food-id="web-milk"]').locator('.catalog-select').click();dialog=page.getByRole('dialog');await dialog.getByLabel('食べた量（ml）',{exact:true}).fill('215');await dialog.getByRole('button',{name:'食事に追加',exact:true}).click();s=await until(s=>s.meals.length===2,'half bottle');assert.equal(s.meals[1].carbs,9.25);assert.equal(s.meals[1].kcal,96.5);assert.equal(s.meals[1].nutrition.values.carbs,18.5);
 await page.getByRole('button',{name:product.name+'を増やす',exact:true}).click();s=await until(s=>s.meals[1].quantity===1,'half back to whole');assert.equal(s.meals[1].carbs,18.5);assert.equal(s.meals[1].kcal,193);
 // Revising a registered product changes future entries and retains its earlier snapshot.
 await page.getByRole('button',{name:'食品を管理',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'使用中',exact:true}).click();await dialog.getByLabel('管理する食品を検索',{exact:true}).fill('メーカー確認済み');await dialog.getByRole('button',{name:'表示値・基準を確認して修正',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('カロリー（kcal）',{exact:true}).fill('200');await dialog.getByRole('button',{name:'食品を保存',exact:true}).click();s=await until(s=>s.foods.find(f=>f.id===product.id)?.kcal===200,'correct saved food');assert.equal(s.meals[1].kcal,193);assert.equal(s.foods.find(f=>f.id===product.id).revisions[0].values.kcal,193);
 await page.getByRole('tab',{name:'食品リスト'}).click();await page.getByLabel('食品を検索',{exact:true}).fill('メーカー確認済み');await page.getByRole('button',{name:product.name+'を1食追加',exact:true}).click();s=await until(s=>s.meals.length===3,'new value');assert.equal(s.meals[2].kcal,200);assert.equal(s.meals[2].nutrition.kind,'manual');assert.equal(s.meals[1].nutrition.kind,'manufacturer');
 await page.getByRole('button',{name:'食品を管理',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'使用中',exact:true}).click();await dialog.getByLabel('管理する食品を検索',{exact:true}).fill('メーカー確認済み');await dialog.getByText('修正履歴（1件）',{exact:true}).click();await dialog.getByRole('button',{name:'この表示値に戻す',exact:true}).click();s=await until(s=>s.foods.find(f=>f.id===product.id).kcal===193,'restore old label');assert.equal(s.meals[2].kcal,200);assert.equal(s.foods.find(f=>f.id===product.id).revisions.length,2);
 await dialog.getByRole('button',{name:'食品リストから非表示',exact:true}).click();await until(s=>s.foods.find(f=>f.id===product.id).archived===true,'archive');await dialog.getByRole('button',{name:'非表示',exact:true}).click();await dialog.getByRole('button',{name:'使用中に戻す',exact:true}).click();await until(s=>s.foods.find(f=>f.id===product.id).archived===false,'unarchive');await dialog.getByRole('button',{name:'閉じる',exact:true}).click();
 // Searching the same exact product again updates the saved reference without duplicating it.
 await page.getByRole('button',{name:'食品・メーカーを探す',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('食品名・JAN・メーカーURL',{exact:true}).fill('カフェラテ430ml');await dialog.getByRole('button',{name:'メーカー表示を検索',exact:true}).click();await dialog.locator('[data-food-id="web-milk"]').locator('.catalog-select').click();await page.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true}).click();s=await state();assert.equal(s.foods.filter(f=>f.name===product.name).length,1);
 // Recipe data retains ingredient values and finished weight for a reproducible later reference.
 await page.getByRole('button',{name:'作り置き計算',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('作り置きの名前',{exact:true}).fill('検証用自作チキン');await dialog.getByRole('button',{name:'材料3を削除',exact:true}).click();await dialog.getByRole('button',{name:'材料2を削除',exact:true}).click();await dialog.getByLabel('使用量（g）',{exact:true}).fill('600');await dialog.getByLabel('調理後の全体重量（g）',{exact:true}).fill('500');await dialog.getByLabel('1食分の重量（g）',{exact:true}).fill('200');await dialog.getByRole('button',{name:'作り置きを保存',exact:true}).click();s=await until(s=>s.foods.some(f=>f.name==='検証用自作チキン'),'recipe');const recipe=s.foods.find(f=>f.name==='検証用自作チキン');assert.equal(recipe.kcal,252);assert.equal(recipe.nutrition.finishedGrams,500);assert.equal(recipe.nutrition.ingredients[0].grams,600);assert.equal(recipe.nutrition.ingredients[0].values.protein,23.3);
 // A response for an old search cannot overwrite the results of a newly typed query.
 await page.getByRole('button',{name:'食品・メーカーを探す',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('食品名・JAN・メーカーURL',{exact:true}).fill('遅い検索');await dialog.getByRole('button',{name:'メーカー表示を検索',exact:true}).click();for(let i=0;i<50&&!waiting;i++)await new Promise(r=>setTimeout(r,20));assert.equal(waiting,true);await dialog.getByLabel('食品名・JAN・メーカーURL',{exact:true}).fill('鶏むね 生');release();await page.waitForTimeout(150);assert.equal(await dialog.locator('[data-food-id="web-milk"]').count(),0);await dialog.locator('[data-food-id="mext-11220"]').waitFor();
 await fs.mkdir('test-artifacts',{recursive:true});for(const width of [390,320]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:`test-artifacts/nutrition-search-${width}.png`,fullPage:true});}await dialog.getByRole('button',{name:'閉じる',exact:true}).click();await page.reload();await page.getByRole('heading',{name:'今日のクエスト'}).waitFor();s=await state();assert.equal(s.meals[1].kcal,193);assert.equal(s.meals[2].kcal,200);assert.equal(s.foods.find(f=>f.id===product.id).revisions.length,2);
 await page.context().setOffline(true);await nav();await page.getByRole('button',{name:'食品・メーカーを探す',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('食品名・JAN・メーカーURL',{exact:true}).fill('鶏むね 生');await dialog.locator('[data-food-id="mext-11220"]').waitFor();assert.equal(await dialog.getByRole('button',{name:'メーカー表示を検索',exact:true}).isDisabled(),true);assert.deepEqual(errors,[]);
 console.log('PASS: 2,537 standard foods; raw 200g reference; manufacturer half/whole precision; correction and revision restore retain past meal snapshots; archive/unarchive; duplicate prevention; recipe ingredients and yield saved; stale search ignored; reload and offline local database; 320/390px');
} catch(e){if(page){await fs.mkdir('test-artifacts',{recursive:true});await page.screenshot({path:'test-artifacts/nutrition-failure.png',fullPage:true});console.log((await page.locator('body').innerText()).slice(-7000));}throw e;} finally {if(browser)await browser.close();server.kill('SIGTERM');}
