import {test} from 'node:test';
import assert from 'node:assert/strict';
import {freshState,validateState} from '../src/domain';
import {defaultEnergy,goalEnergy,mealBudget,weeklyBudget} from '../src/energy';
import {goalName,monthsAfter,nutritionPlan,planError,planReady,syncNutrition} from '../src/planning';
import {aiContext} from '../src/ai';
function fixture(){const s=freshState();s.settings={...s.settings,startWeight:80,targetWeight:75,startDate:'2026-10-02',deadline:'2027-10-02',energy:{...defaultEnergy,age:35,height:175,activity:1.35},goalName:'来年の旅行',nutritionMode:'auto'};return s;}
test('new users get no invented profile or weight goal; backups preserve manual settings',()=>{const s=freshState();assert.equal(planReady(s.settings),false);assert.equal(nutritionPlan(s),null);assert.equal(goalEnergy(s).loss,0);assert.equal(goalName(s.settings),'自分の目標');const legacy=fixture();delete legacy.settings.nutritionMode;legacy.settings.kcal=2100;assert.equal(syncNutrition(validateState(legacy)).settings.kcal,2100);});
test('event goal synchronizes calorie, PFC, meal allocation, weekly allowance and AI context',()=>{const s=syncNutrition(fixture(),'2026-10-02'),n=nutritionPlan(s,'2026-10-02')!;assert.equal(s.settings.kcal,n.kcal);assert.equal(s.settings.protein,128);assert.ok(Math.abs(n.protein*4+n.fat*9+n.carbs*4-n.kcal)<=2);assert.equal(mealBudget(s,'2026-10-02').planned.reduce((sum,m)=>sum+m.kcal,0),n.kcal);assert.equal(weeklyBudget(s,'2026-10-02','2026-10-02').days* s.settings.kcal,3*n.kcal);assert.equal(aiContext(s,'2026-10-02').settings.protein,n.protein);assert.equal(aiContext(s,'2026-10-02').settings.goalName,'来年の旅行');});
test('new measurements update auto nutrition without altering recorded meals or closed days',()=>{const s=fixture();s.closedDays={'2026-10-02':{weight:80,expenditure:2200}};const old=syncNutrition(s,'2026-10-02');s.weights=[{id:'w',date:'2026-11-02',time:'朝',kg:77}];const next=syncNutrition(s,'2026-11-02');assert.notEqual(next.settings.protein,old.settings.protein);assert.equal(next.settings.protein,123);assert.deepEqual(next.closedDays,old.closedDays);assert.deepEqual(next.meals,old.meals);});
test('manual nutrition survives weight and deadline updates',()=>{const s=fixture();s.settings.nutritionMode='manual';s.settings.kcal=1800;s.settings.protein=99;s.weights=[{id:'w',date:'2026-11-02',time:'朝',kg:77}];const next=syncNutrition(s,'2026-11-02');assert.equal(next.settings.kcal,1800);assert.equal(next.settings.protein,99);});
test('short deadline is capped; expired goals use maintenance, never compensation',()=>{const s=fixture();s.settings.deadline='2026-10-03';const n=nutritionPlan(s,'2026-10-02')!;assert.equal(n.limited,true);assert.ok(n.deficit<=n.expenditure*.2+10);assert.ok(n.kcal>=1600);const expired=nutritionPlan(s,'2026-10-04')!;assert.equal(expired.expired,true);assert.ok(Math.abs(expired.deficit)<=5);});
test('maintenance and low energy profile retain valid PFC and minimum intake',()=>{const s=fixture();s.settings.startWeight=55;s.settings.targetWeight=55;s.settings.energy={...defaultEnergy,sex:'female',age:70,height:155,activity:1.2};const n=nutritionPlan(s,'2026-10-02')!;assert.equal(n.kcal,1600);assert.ok(n.carbs>0);assert.ok(n.protein*4<=n.kcal*.3);});
test('long-term dates clamp end-of-month and handle leap years',()=>{assert.equal(monthsAfter('2026-01-31',1),'2026-02-28');assert.equal(monthsAfter('2024-02-29',12),'2025-02-28');assert.equal(monthsAfter('2026-10-02',12),'2027-10-02');});
test('unsafe target and invalid imported preferences are rejected; old data remains loadable',()=>{const s=fixture();s.settings.startDate='2020-01-01';s.settings.deadline='2030-01-01';assert.equal(planError(s.settings),'');s.settings.targetWeight=40;assert.match(planError(s.settings),/BMI/);assert.throws(()=>validateState({...s,settings:{...s.settings,coachMode:'abusive'}}));assert.throws(()=>validateState({...s,settings:{...s.settings,proteinPerKg:99}}));assert.throws(()=>validateState({...s,favorites:[null]}));assert.deepEqual(validateState(s),s);});
