import {test} from 'node:test';
import assert from 'node:assert/strict';
import {freshState,offsetDate,validateState} from '../src/domain';
import {isStrength,menus,recommendMenu,trainingWeek} from '../src/training';
import {validSets,volume,setComparisons,validTraining} from '../src/workoutData';
import {aiContext,exerciseAiContext} from '../src/ai';
import type {Exercise,StrengthSet} from '../src/types';
const date='2026-10-08';
const session=(id:string,d:string,name:string,sets?:StrengthSet[]):Exercise=>({id,date:d,name,minutes:60,details:'',kind:'strength',...(sets?{sets}:{})});
const set=(kg:number,reps=10,warmup=false):StrengthSet=>({exercise:'ベンチプレス',kg,reps,rir:2,warmup});
const advanced=()=>{const s=freshState();s.settings.training={mode:'advanced',goal:'hypertrophy',weeklyDays:4,minutes:60};return s;};
test('typed cardio is not mistaken for strength, including gym-bike labels; old workouts still work',()=>{assert.equal(isStrength({...session('a',date,'ジムでバイク'),kind:'cardio'}),false);assert.equal(isStrength(session('a',date,'胸の日')),true);assert.equal(isStrength({id:'l',date,name:'ベンチプレス',minutes:30,details:''}),true);});
test('experienced split can train different muscles on consecutive days and exceeds a generic 3/week cap',()=>{const s=advanced(),upper=menus.find(m=>m.id==='gym-upper')!,lower=menus.find(m=>m.id==='gym-lower')!;s.exercises=[session('1',offsetDate(date,-3),upper.name),session('2',offsetDate(date,-2),lower.name),session('3',offsetDate(date,-1),upper.name)];assert.equal(trainingWeek(s,date).strengthDays,3);assert.equal(trainingWeek(s,date).target,4);assert.equal(recommendMenu(s,date,'在宅',false).menu.id,'gym-lower');s.settings.training!.weeklyDays=6;assert.equal(trainingWeek(s,date).maximum,6);});
test('experienced recommendations respect fatigue/recovery when the previous muscles are unknown, and pain wins',()=>{const s=advanced();s.exercises=[session('1',offsetDate(date,-1),'自分のメニュー')];assert.equal(recommendMenu(s,date,'出社',false).menu.id,'walk-easy');assert.equal(recommendMenu(s,date,'出社',true).menu.id,'pain');});
test('walking/home/gym preferences supersede work-location assumptions',()=>{const s=advanced();s.settings.training!.mode='walking';assert.equal(recommendMenu(s,date,'出社',false).menu.id,'walk-easy');assert.equal(trainingWeek(s,date).target,0);s.settings.training!.mode='home';assert.equal(recommendMenu(s,date,'出社',false).menu.id,'home10');s.settings.training!.mode='gym';assert.equal(recommendMenu(s,date,'在宅',false).menu.id,'gym-a');});
test('work-set load excludes warmups; per-exercise comparisons never merge different movements',()=>{const sets=[set(40,10,true),set(80,8),{exercise:'スクワット',kg:100,reps:5}];assert.equal(volume(sets),1140);const h=[session('1',offsetDate(date,-3),'上半身',[set(40,10,true),set(75,8)]),session('2',offsetDate(date,-1),'下半身',[{exercise:'スクワット',kg:100,reps:5}])];const c=setComparisons(h,sets,date);assert.equal(c[0].previousBest,75);assert.equal(c[0].previousVolume,600);assert.equal(c[0].currentVolume,640);assert.equal(c[0].sets,1);assert.equal(c[1].previousVolume,500);assert.equal(setComparisons([session('future',offsetDate(date,1),'上半身',[set(200)])],[set(80)],date)[0].previousVolume,null);});
test('optional preferences and sets round-trip with old backups; invalid metrics are rejected',()=>{const s=advanced();s.exercises=[session('1',date,'ベンチ',[set(80)])];assert.deepEqual(validateState(s).exercises[0].sets,[set(80)]);assert.ok(validateState(freshState()));for(const bad of [{...set(80),kg:-1},{...set(80),reps:0},{...set(80),reps:2.5},{...set(80),rir:11},{...set(80),exercise:''}])assert.equal(validSets([bad]),false);assert.equal(validSets(Array.from({length:61},()=>set(80))),false);assert.equal(validTraining({...s.settings.training,weeklyDays:7}),false);assert.throws(()=>validateState({...s,exercises:[{...s.exercises[0],kind:'cardio'}]}));});
test('AI gets mode, weekly target, measured sets and a bounded recent context',()=>{const s=advanced();s.exercises=Array.from({length:20},(_,i)=>({...session(String(i),offsetDate(date,-i),'長い記録',Array.from({length:60},()=>({...set(80),exercise:'x'.repeat(100)}))),details:'x'.repeat(3000)}));const ctx=exerciseAiContext(s,date,menus.map(m=>m.name));assert.equal(ctx.training?.weeklyDays,4);assert.equal(ctx.recentExercises.length,10);assert.equal(ctx.recentExercises[0].sets?.length,8);assert.equal(ctx.recentExercises[0].setsOmitted,52);assert.equal(ctx.recentExercises[0].loggedWorkSets,60);assert.ok(JSON.stringify(ctx).length<30000);assert.equal(aiContext(s,date).today.trainingThisWeek.target,4);});

test('same-date previous sessions resolve to the most recently appended entry',()=>{const h=[session('old',offsetDate(date,-1),'ベンチ',[set(70)]),session('new',offsetDate(date,-1),'ベンチ',[set(75)])];assert.equal(setComparisons(h,[set(80)],date)[0].previousBest,75);});

test('coach distinguishes today recovery from tomorrow different-muscle split',()=>{const state=freshState();state.settings.training={mode:'advanced',goal:'strength',weeklyDays:4,minutes:60};state.exercises=[session('today',date,'ジム本格・上半身',[set(80)])];const ctx=aiContext(state,date);assert.equal(ctx.today.suggestedWorkout.name,'回復・ストレッチ10分');assert.equal(ctx.today.nextWorkoutExample?.name,'ジム本格・下半身');assert.equal(ctx.today.nextWorkoutExample?.date,offsetDate(date,1));state.painDates=[offsetDate(date,1)];assert.equal(aiContext(state,date).today.nextWorkoutExample?.name,'回復を優先');});
