import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import fs from 'node:fs/promises';
const {chromium}=await import(process.env.BODY_QUEST_PLAYWRIGHT??'playwright');
const server=spawn('node',['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','4190'],{stdio:'inherit'});let browser;
try {
 for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:4190')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch(process.env.BODY_QUEST_CHROMIUM?{executablePath:process.env.BODY_QUEST_CHROMIUM,args:['--no-sandbox']}:{});
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));
 const read=()=>page.evaluate(async()=>{const db=await new Promise((r,j)=>{const q=indexedDB.open('body-quest',1);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});return new Promise((r,j)=>{const q=db.transaction('data').objectStore('data').get('state');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});});
 const until=async(check,label)=>{for(let i=0;i<100;i++){const s=await read();if(s&&check(s))return s;await new Promise(r=>setTimeout(r,50));}throw new Error('not persisted: '+label);};
 await page.route('**/api/assistant',async route=>{if(route.request().method()!=='POST')return route.fulfill({json:{configured:true}});const b=route.request().postDataJSON();requests.push(b);return route.fulfill({json:b.task==='exercise'?{exercises:[{name:'ベンチプレス',minutes:30,met:3.5,kind:'strength',details:'80kg 8回×2',note:'',sets:[{exercise:'ベンチプレス',kg:80,reps:8,rir:2},{exercise:'ベンチプレス',kg:80,reps:8,rir:1}]}]}:{text:'【前回比較】\n前回のセットをもとに提案します。'}});});
 const day=new Date(),iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,date=iso(day),ago=n=>{const d=new Date(day);d.setDate(d.getDate()-n);return iso(d);};
 await page.goto('http://127.0.0.1:4190');await until(s=>!!s,'initial');
 await page.evaluate(async({date,start,deadline,previous})=>{const db=await new Promise(r=>{const q=indexedDB.open('body-quest',1);q.onsuccess=()=>r(q.result)}),s=await new Promise(r=>{const q=db.transaction('data').objectStore('data').get('state');q.onsuccess=()=>r(q.result)});s.settings={...s.settings,startWeight:80,targetWeight:75,startDate:start,deadline,energy:{age:40,height:175,sex:'male',activity:1.35,exerciseMode:'separate',weeklyExerciseKcal:0},nutritionMode:'manual',kcal:2200};s.exercises=[{id:'previous',date:previous,name:'ジム本格・上半身',minutes:60,met:3.5,details:'',kind:'strength',sets:[{exercise:'ベンチプレス',kg:40,reps:10,warmup:true},{exercise:'ベンチプレス',kg:75,reps:8,rir:2},{exercise:'ベンチプレス',kg:75,reps:8,rir:2}]}];await new Promise(r=>{const tx=db.transaction('data','readwrite');tx.objectStore('data').put(s,'state');tx.oncomplete=r;});},{date,start:ago(14),deadline:`${day.getFullYear()+1}-12-01`,previous:ago(3)});
 await page.reload();const nav=name=>page.locator('.bottom-nav').getByRole('button',{name,exact:true}).click();await nav('運動');
 await page.locator('.training-mode-grid').getByRole('button',{name:/歩く・消費/}).click();await until(s=>s.settings.training?.mode==='walking','walking mode');
 await page.locator('.walk-quick-grid').getByRole('button',{name:/1駅分歩く/}).click();const form=page.locator('#exercise-form form');assert.equal(await form.getByLabel('時間（分）',{exact:true}).inputValue(),'15');await form.getByLabel('時間（分）',{exact:true}).fill('20');await form.getByRole('button',{name:'運動を保存',exact:true}).click();let s=await until(s=>s.exercises.some(e=>e.name==='1駅分歩く'),'walking');const walking=s.exercises.find(e=>e.name==='1駅分歩く');assert.equal(walking.kind,'cardio');assert.equal(walking.netKcal,48);assert.equal(s.settings.kcal,2200);
 await page.locator('.training-mode-grid').getByRole('button',{name:/ジム・本格/}).click();await until(s=>s.settings.training?.mode==='advanced','advanced mode');await page.locator('.training-custom summary').click();await page.getByLabel('トレーニングの目的',{exact:true}).selectOption('strength');await until(s=>s.settings.training?.goal==='strength','strength goal');
 const upper=page.locator('.training-plan').filter({has:page.getByRole('heading',{name:'ジム本格・上半身',exact:true})});if(await upper.getByRole('button',{name:'種目を見る',exact:true}).count())await upper.getByRole('button',{name:'種目を見る',exact:true}).click();await upper.getByRole('button',{name:'このメニューを記録する',exact:true}).click();
 assert.equal(await form.locator('.set-row').count(),3);assert.equal(await form.locator('.set-row').first().getByLabel('ウォームアップ',{exact:true}).isChecked(),true);
 for(const i of [1,2])await form.locator('.set-row').nth(i).getByLabel('重量（kg）',{exact:true}).fill('80');await form.locator('.set-row').nth(2).getByRole('button',{name:'同じ種目のセットを追加',exact:false}).click();
 await form.locator('.set-summary').getByText(/前回.*2セット/).waitFor();await context.setOffline(true);await form.getByRole('button',{name:'運動を保存',exact:true}).click();s=await until(s=>s.exercises.some(e=>e.date===date&&e.sets?.length===4),'sets offline');const saved=s.exercises.find(e=>e.date===date&&e.sets?.length===4);assert.equal(saved.kind,'strength');assert.equal(saved.sets[0].warmup,true);assert.equal(saved.sets[1].kg,80);await context.setOffline(false);
 // Editing replaces the record and invalidates a previously confirmed day.
 await page.evaluate(async date=>{const db=await new Promise(r=>{const q=indexedDB.open('body-quest',1);q.onsuccess=()=>r(q.result)}),s=await new Promise(r=>{const q=db.transaction('data').objectStore('data').get('state');q.onsuccess=()=>r(q.result)});s.closedDays={[date]:{weight:80,expenditure:2300}};await new Promise(r=>{const tx=db.transaction('data','readwrite');tx.objectStore('data').put(s,'state');tx.oncomplete=r;});},date);await page.reload();await nav('運動');
 const recorded=page.locator('#exercise-form .record-row').filter({hasText:'ジム本格・上半身'});await recorded.getByRole('button',{name:'この記録を修正',exact:true}).click();await form.locator('.set-row').nth(1).getByLabel('重量（kg）',{exact:true}).fill('85');await form.getByRole('button',{name:'運動を更新',exact:true}).click();s=await until(s=>s.exercises.find(e=>e.id===saved.id)?.sets?.[1].kg===85,'edit');assert.equal(s.exercises.filter(e=>e.id===saved.id).length,1);assert.equal(s.closedDays?.[date],undefined);
 await recorded.locator('summary').click();await recorded.getByText(/前回.*2セット/).waitFor();
 // A date switch clears an edit so another day's workout isn't changed by mistake.
 await recorded.getByRole('button',{name:'この記録を修正',exact:true}).click();await page.getByRole('button',{name:'前の日',exact:true}).click();await form.getByRole('button',{name:'運動を保存',exact:true}).waitFor();assert.equal(await form.getByRole('button',{name:'運動を更新',exact:true}).count(),0);await page.getByRole('button',{name:'次の日',exact:true}).click();
 // AI parsing supplies actual sets to review and edit, then persists them in the same schema.
 await page.locator('.exercise-ai textarea').first().fill('ベンチプレス80kg 8回2セット、余力2回と1回。30分。');await page.getByRole('button',{name:'AIで読み取る',exact:true}).click();await page.locator('.exercise-draft .set-row').nth(1).waitFor();await page.locator('.exercise-draft .set-row').first().getByLabel('重量（kg）',{exact:true}).fill('82.5');await page.locator('.exercise-draft').getByRole('button',{name:'確認して記録',exact:true}).click();s=await until(s=>s.exercises.some(e=>e.name==='ベンチプレス'&&e.sets?.[0].kg===82.5),'AI sets');assert.equal(requests.at(-1).context.training.weeklyDays,4);assert.equal(requests.at(-1).context.training.goal,'strength');assert.ok(requests.at(-1).context.recentExercises.some(e=>e.sets?.length));
 await page.reload();await nav('運動');await until(s=>s.settings.training?.mode==='advanced'&&s.exercises.find(e=>e.id===saved.id)?.sets?.[1].kg===85,'reload');
 await page.getByRole('button',{name:'AIにメニューを組んでもらう',exact:true}).click();await page.locator('.coach-panel').getByRole('button',{name:'相談する',exact:true}).click();await page.getByText('【前回比較】',{exact:true}).waitFor();assert.equal(requests.at(-1).context.settings.training.weeklyDays,4);assert.ok(requests.at(-1).context.exercises.some(e=>e.sets?.some(s=>s.kg===85)));assert.equal(requests.at(-1).context.today.trainingThisWeek.target,4);
 await nav('運動');await fs.mkdir('test-artifacts',{recursive:true});for(const width of [390,320]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('.training-preferences').screenshot({path:`test-artifacts/training-styles-${width}.png`});}
 assert.deepEqual(errors,[]);console.log('PASS: walking duration/net kcal and no food-target inflation; styles and advanced split; prior sets, warmup, volume comparison; offline save/edit/closure invalidation/reload; date edit guard; AI parsed editable sets and coach context; 320/390px');
}finally{if(browser)await browser.close();server.kill('SIGTERM');}
