import {useEffect,useRef,useState} from 'react';
import {Search,Archive,RotateCcw,ExternalLink,Star} from 'lucide-react';
import {Field,Empty} from './ui';
import type {Food,NutritionBasis} from './types';
import {loadComposition,searchComposition} from './composition';
import {nutritionIssues,preparationLabels,searchFoods,sourceLabels} from './nutrition';
export function NutritionDetails({nutrition,source}:{nutrition?:NutritionBasis;source:string}) {
 return <details className="nutrition-details"><summary>計算の根拠</summary>{nutrition?<><p><strong>{sourceLabels[nutrition.kind]}</strong> · {preparationLabels[nutrition.preparation]}</p><p>基準：{nutrition.portion}<br/>{nutrition.values.kcal.toFixed(1).replace(/\.0$/,'')} kcal · P {nutrition.values.protein.toFixed(1)} / F {nutrition.values.fat.toFixed(1)} / C {nutrition.values.carbs.toFixed(1)} g</p>{nutrition.url?<a href={nutrition.url} target="_blank" rel="noopener noreferrer">出典のページを確認 <ExternalLink size={13}/></a>:null}{nutrition.checkedAt?<p className="muted">確認日：{new Date(nutrition.checkedAt).toLocaleDateString('ja-JP')}</p>:null}{nutrition.ingredients?<details><summary>材料と完成重量</summary><p>完成後の全体重量：{nutrition.finishedGrams}g。材料の成分値を合算して取り分けを計算しています。</p>{nutrition.ingredients.map((i,n)=><p key={n}>{i.name} {i.grams}g<br/><small>材料100gあたり：{i.values.kcal} kcal / P{i.values.protein} / F{i.values.fat} / C{i.values.carbs}g {i.url?<a href={i.url} target="_blank" rel="noopener noreferrer">出典</a>:null}</small></p>)}</details>:null}</>:<p>この食品は以前の形式で保存されています。表示値に対応する量・出典・調理状態を確認すると、次回の計算にも使えます。</p>}<p className="muted">{source}</p></details>;
}
type SearchResponse={foods:Food[];sources:{title:string;url:string}[];searchSuggestions?:string;searchedAt:string;note:string};
export function FoodSearch({initialQuery,foods,online,choose}:{initialQuery:string;foods:Food[];online:boolean;choose:(food:Food)=>void}) {
 const [query,setQuery]=useState(initialQuery),[standard,setStandard]=useState<Food[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[remote,setRemote]=useState<SearchResponse>(),[loaded,setLoaded]=useState(false);const generation=useRef(0),abort=useRef<AbortController|null>(null);
 useEffect(()=>{let active=true;loadComposition().then(f=>{if(active){setStandard(f);setLoaded(true);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;generation.current++;abort.current?.abort();};},[]);
 const local=query.trim()?searchFoods(foods,query,[],8):[],composition=searchComposition(standard,query),results=[...local,...composition.filter(f=>!local.some(x=>x.id===f.id))];
 const change=(q:string)=>{generation.current++;abort.current?.abort();setQuery(q);setRemote(undefined);setError('');setBusy(false);};
 async function search(){const token=++generation.current;abort.current?.abort();const controller=new AbortController;abort.current=controller;setBusy(true);setError('');setRemote(undefined);try{const r=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task:'foodSearch',text:query.trim(),context:{}}),signal:AbortSignal.any([controller.signal,AbortSignal.timeout(60000)])});const data=await r.json();if(!r.ok)throw Error(data.error??'検索できませんでした');if(generation.current===token)setRemote(data);}catch(e){if(generation.current===token&&!(e instanceof Error&&e.name==='AbortError'))setError(e instanceof Error?e.message:'検索できませんでした');}finally{if(generation.current===token)setBusy(false);}}
 const result=(f:Food)=><div className="catalog-result" data-food-id={f.id} key={f.id}><button className="catalog-select" onClick={()=>choose(f)}><strong>{f.name}</strong><small>{f.portion} · {f.nutrition?sourceLabels[f.nutrition.kind]:f.estimated?'推定値':'登録値'}</small><span>{Math.round(f.kcal)} kcal · P {f.protein.toFixed(1)}g <span className="catalog-action">量を指定 →</span></span></button><NutritionDetails nutrition={f.nutrition} source={f.source}/></div>;
 return <div className="food-search"><Field label="食品名・JAN・メーカーURL"><input type="search" aria-label="食品名・JAN・メーカーURL" value={query} onChange={e=>change(e.target.value)} maxLength={300} placeholder="鶏むね 生 ／ ザバス カフェラテ 430ml"/></Field><p className="muted">登録食品と文科省の標準食品はすぐに検索。市販品はメーカー表示を検索し、味・容量の合う商品を選びます。主要メーカーの公式商品一覧を優先し、必要な場合はGoogleで探します。検索語を検索先に送ります。</p><button className="primary" disabled={busy||!online||query.trim().length<2} onClick={search}><Search size={17}/>{busy?'メーカーの表示を探しています…':'メーカー表示を検索'}</button>{error?<p className="error" role="alert">{error}</p>:null}{remote?<section aria-label="メーカーの検索結果"><p>{remote.note}</p>{remote.foods.map(result)}{remote.sources.length?<details><summary>検索した出典</summary>{remote.sources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title}</a></p>)}</details>:null}{remote.searchSuggestions?<iframe title="Google検索の候補" sandbox="allow-popups allow-popups-to-escape-sandbox" srcDoc={remote.searchSuggestions} className="search-suggestions"/>:null}</section>:null}{results.length?<section aria-label="登録・標準食品の検索結果"><h3>登録・標準食品</h3>{results.map(result)}</section>:query.trim()&&!loading?<Empty>登録・標準食品に一致する候補がありません。メーカー検索や、栄養表示の写真から登録できます。</Empty>:null}{loading?<p role="status" className="muted">標準食品を読み込んでいます…</p>:loaded?<p className="muted">文科省の標準食品 {standard.length.toLocaleString()}件。日本食品標準成分表（八訂）増補2023年・2026年訂正データから引用。可食部100gあたりの標準値で、個々の商品・調理による変動があります。</p>:null}</div>;
}
export function FoodManager({foods,favorites=[],favorite,edit,archive,restore}:{foods:Food[];favorites?:string[];favorite?:(f:Food)=>void;edit:(f:Food)=>void;archive:(f:Food)=>void;restore:(f:Food,index:number)=>void}) {
 const [query,setQuery]=useState(''),[mode,setMode]=useState<'all'|'review'|'archived'>('review');const review=foods.filter(f=>!f.archived&&nutritionIssues(f).length),filtered=foods.filter(f=>(mode==='archived'?f.archived:!f.archived)&&(mode!=='review'||nutritionIssues(f).length)&&(!query.trim()||searchFoods([{...f,archived:false}],query).length));
 return <div className="food-manager"><p className="muted">修正は次回からの入力に反映されます。過去の食事は、その日に保存した値と出典を保持します。非表示にした食品はいつでも戻せます。</p><div className="filter-chips">{([['review',`要確認 ${review.length}`],['all','使用中'],['archived','非表示']] as const).map(([id,label])=><button key={id} className={mode===id?'selected':''} onClick={()=>setMode(id)}>{label}</button>)}</div><Field label="管理する食品を検索"><input aria-label="管理する食品を検索" type="search" value={query} onChange={e=>setQuery(e.target.value)}/></Field>{filtered.slice(0,30).map(f=><div className="catalog-result" data-food-id={f.id} key={f.id}><strong>{f.name}</strong><p className="muted">{f.portion} · {Math.round(f.kcal)} kcal · P{f.protein.toFixed(1)}g{f.revision?` · 更新${f.revision}回目`:''}</p>{nutritionIssues(f).map(issue=><p key={issue} className="food-quality-note">{issue}</p>)}<NutritionDetails nutrition={f.nutrition} source={f.source}/><div className="quick-actions"><button className="secondary" onClick={()=>edit(f)}>表示値・基準を確認して修正</button>{favorite&&!f.archived?<button className="text-button favorite-button" aria-pressed={favorites.includes(f.id)} onClick={()=>favorite(f)}><Star size={15} fill={favorites.includes(f.id)?'currentColor':'none'}/> {favorites.includes(f.id)?'お気に入り登録済み':'お気に入りに登録'}</button>:null}<button className="text-button" onClick={()=>archive(f)}>{f.archived?<RotateCcw size={15}/>:<Archive size={15}/>} {f.archived?'使用中に戻す':'食品リストから非表示'}</button></div>{f.revisions?.length?<details><summary>修正履歴（{f.revisions.length}件）</summary>{f.revisions.map((r,i)=><div key={r.at+i}><p>{new Date(r.at).toLocaleString('ja-JP')}<br/>{r.name} · {r.portion} · {r.values.kcal.toFixed(1)} kcal / P{r.values.protein.toFixed(1)}g</p><button className="text-button" onClick={()=>restore(f,i)}>この表示値に戻す</button></div>)}</details>:null}</div>)}{!filtered.length?<Empty>{mode==='review'?'確認が必要な登録食品はありません。':'該当する食品がありません。'}</Empty>:null}{filtered.length>30?<p className="muted">先頭30件を表示しています。食品名で絞り込めます。</p>:null}</div>;
}
