import type {AppState,TrainingProfile} from './types';
import {trainingModes} from './workoutData';
import {Field} from './ui';
export function TrainingPreferences({state,save}:{state:AppState;save:(profile:TrainingProfile)=>void}) {
 const profile=state.settings.training;
 return <details className="card training-preferences" open={!profile}><summary className="training-style-summary">運動スタイル<strong>{trainingModes.find(m=>m.id===profile?.mode)?.label??'選ぶ'}</strong></summary><div className="training-style-body"><span className="eyebrow lime">YOUR TRAINING STYLE</span><h2>今日は、どんな運動を？</h2><div className="training-mode-grid">{trainingModes.map(m=><button key={m.id} aria-pressed={profile?.mode===m.id} className={profile?.mode===m.id?'selected':''} onClick={()=>{if(profile?.mode!==m.id)save({mode:m.id,goal:m.goal,weeklyDays:m.weeklyDays,minutes:m.minutes});}}><strong>{m.label}</strong><small>{m.detail}</small></button>)}</div>
 {profile?.mode==='advanced'?<details className="training-custom"><summary>{profile.goal==='strength'?'筋力向上':profile.goal==='hypertrophy'?'筋肥大':'体力づくり'} · 週{profile.weeklyDays}回 · {profile.minutes}分／回 <span>方針を調整</span></summary><div className="form-grid"><Field label="トレーニングの目的"><select aria-label="トレーニングの目的" value={profile.goal} onChange={e=>save({...profile,goal:e.target.value as TrainingProfile['goal']})}><option value="hypertrophy">筋肥大・筋肉を残す</option><option value="strength">筋力・使用重量を伸ばす</option><option value="fitness">健康・体力づくり</option></select></Field><Field label="週の筋トレ予定"><select aria-label="週の筋トレ予定" value={profile.weeklyDays} onChange={e=>save({...profile,weeklyDays:Number(e.target.value)})}>{[2,3,4,5,6].map(n=><option value={n} key={n}>週{n}回</option>)}</select></Field><Field label="1回の予定時間"><select aria-label="1回の予定時間" value={profile.minutes} onChange={e=>save({...profile,minutes:Number(e.target.value)})}>{[30,45,60,90,120].map(n=><option key={n} value={n}>{n}分</option>)}</select></Field></div><p className="muted">上半身／下半身の分割は一例です。自分のメニューも記録できます。AIには目的・頻度とセット履歴が伝わります。</p></details>:<p className="muted">選んだスタイルを次回にも使います。歩く日も、家で鍛える日も、切り替えてOK。</p>}
 </div></details>;
}
