import {useEffect, useRef, useState, type InputHTMLAttributes, type ReactNode} from 'react';
import {X} from 'lucide-react';
export function Modal({title,children,close}:{title:string;children:ReactNode;close:()=>void}) {const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();const listener=(event:KeyboardEvent)=>{if(event.key==='Escape')close();if(event.key==='Tab'){const all=ref.current?.querySelectorAll<HTMLElement>('button,input,select,textarea,a[href]');if(!all?.length)return;const first=all[0],last=all[all.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}};document.addEventListener('keydown',listener);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',listener);previous?.focus();};},[close]);return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><div ref={ref} className="modal" role="dialog" aria-modal="true" aria-label={title} tabIndex={-1}><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="閉じる"><X/></button></div>{children}</div></div>;}
export function Field({label,children}:{label:string;children:ReactNode}) {return <label className="field"><span>{label}</span>{children}</label>;}
export function Empty({children}:{children:ReactNode}) {return <div className="empty">{children}</div>;}
export function NutritionInputs({values,onChange}:{values:{kcal:number;protein:number;fat:number;carbs:number};onChange:(key:'kcal'|'protein'|'fat'|'carbs',value:number)=>void}) {return <div className="form-grid">{([['kcal','カロリー（kcal）'],['protein','たんぱく質（g）'],['fat','脂質（g）'],['carbs','炭水化物（g）']] as const).map(([key,label])=><Field label={label} key={key}><NumberInput min="0" max="50000" step="0.1" inputMode="decimal" required digits={1} value={values[key]} onValue={v=>onChange(key,v)}/></Field>)}</div>;}
// Keeps what is being typed ("", "1.", "15") instead of re-rendering the parsed number, so a 0 can be cleared and typing never yields "01".
export function NumberInput({value,onValue,digits=3,onFocus,...rest}:Omit<InputHTMLAttributes<HTMLInputElement>,'value'|'onChange'|'type'>&{value:number;onValue:(value:number)=>void;digits?:number}) {const shown=(n:number)=>Number.isFinite(n)?String(Number(n.toFixed(digits))):'';const [text,setText]=useState(()=>shown(value)),[seen,setSeen]=useState(value);const parsed=text.trim()===''?0:Number(text);
 // Follow values changed from outside (presets, ×1.5 chips, the linked g and 倍 fields) in the same render, without fighting the keyboard.
 if(!Object.is(seen,value)){setSeen(value);if(!(Math.abs(parsed-value)<=1e-9*Math.max(1,Math.abs(value))))setText(shown(value));}
 return <input {...rest} type="number" value={text} onFocus={e=>{e.currentTarget.select();onFocus?.(e);}} onChange={e=>{const raw=e.target.value.replace(/^(-?)0+(?=\d)/,'$1');setText(raw);onValue(raw.trim()===''?0:Number(raw));}}/>;}
